/*
 * ================================================================
 * FileName: main.c
 * Lab 10: ADC-Based Servo Control
 * Author: Yash Bhandari
 * Created: 3/25/2025
 * ================================================================
 *
 * Operations:
 *   Reads an analog voltage from a potentiometer using the ADC,
 *   maps the 8-bit digital value (0–255) to a servo angle (0–180°),
 *   and controls the servo motor position using a PWM signal
 *   generated by Timer3. The ADC value is displayed on PORTA
 *   as a live visual output on an LED bar.
 *
 * Hardware:
 *   Atmega2560          microcontroller
 *   PORTF.1 (ADC1)      potentiometer analog input (0–5V)
 *   PORTE.4 (OC3B)      PWM output to servo motor
 *   PORTA[7:0]          LED bar display for ADC output
 */

#include <avr/io.h>
#include <avr/interrupt.h>
#include "ADC.h"
#include "servo.h"

/* NOTE: Global Variables */
volatile uint8_t adc_value;    // stores 8-bit ADC result

/* NOTE: Function prototypes */
// none required for this file; all initialization and control handled in main()

/* NOTE: Application implementation */
int main(void)
{
    // enable global interrupts
    sei();

    // initialize ADC and I/O ports
    IO_init();

    // initialize Timer3 for servo PWM control
    initServo();

    // continuously read ADC and adjust servo position
    while (1)
    {
        // output the ADC value to LED bar on PORTA
        PORTA = adc_value;

        // map ADC value (0–255) to servo angle (0–180°)
        // and send position to servo
        servo_deg((adc_value / 255.0) * 180);
    }
}
